global using BuildingBlocks.CQRS;
global using Carter;
global using Catalog.Api.Data;
global using Catalog.Api.Dtos;
global using Catalog.Api.Models;
global using FluentValidation;
global using Mapster;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
