global using Basket.Api.Data;
global using Basket.Api.Model;
global using BuildingBlocks.CQRS;
global using Carter;
global using Mapster;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Basket.Api.Dtos;
global using Basket.Api.Common;