version: '3.4'

services:
  catalog.db:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    volumes:
      - bookstore_catalog:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
  
  basket.db:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    volumes:
      - bookstore_basket:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  messagebroker:
    container_name: bookstoremessagebroker
    hostname: bookstore-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    

